import { TALENTS_MONK } from 'common/TALENTS/monk';
import { Talent } from 'common/TALENTS/types';

export const COALESENCE_INCREASE = 0.2;

// talent tree order, used to order statistics (position 0 is the hero talent summary)
// top talent, each column from left to right, then capstone
export const HARMONY_TALENT_ORDER: Talent[] = [
  TALENTS_MONK.ASPECT_OF_HARMONY_TALENT,
  TALENTS_MONK.MANIFESTATION_TALENT,
  TALENTS_MONK.OVERWHELMING_FORCE_TALENT,
  TALENTS_MONK.PURIFIED_SPIRIT_TALENT,
  TALENTS_MONK.HARMONIC_GAMBIT_TALENT,
  TALENTS_MONK.ENDLESS_DRAUGHT_TALENT,
  TALENTS_MONK.PATH_OF_RESURGENCE_TALENT,
  TALENTS_MONK.WAY_OF_A_THOUSAND_STRIKES_TALENT,
  TALENTS_MONK.BALANCED_STRATAGEM_TALENT,
  TALENTS_MONK.MANTRA_OF_PURITY_TALENT,
  TALENTS_MONK.MANTRA_OF_TENACITY_TALENT,
  TALENTS_MONK.CLARITY_OF_PURPOSE_TALENT,
  TALENTS_MONK.HARMONIC_SURGE_TALENT,
  TALENTS_MONK.POTENTIAL_ENERGY_TALENT,
  TALENTS_MONK.MEDITATIVE_FOCUS_TALENT,
  TALENTS_MONK.COALESCENCE_TALENT,
];
