import SPELLS from 'common/SPELLS';
import { TALENTS_MONK } from 'common/TALENTS/monk';
import { Talent } from 'common/TALENTS/types';

export const CELESTIAL_CONDUIT_MAX_DURATION = 4000;
export const CELESTIAL_CONDUIT_INCREASE_PER_TARGET = 0.06;
export const CELESTIAL_CONDUIT_MAX_TARGETS = 5;
export const RESTORE_BALANCE_BOOST = 0.05;
export const MISTWEAVER_HEART_SPELLS = (hasRWK: boolean): number[] => [
  SPELLS.RENEWING_MIST_CAST.id,
  hasRWK
    ? TALENTS_MONK.RUSHING_WIND_KICK_MISTWEAVER_TALENT.id
    : TALENTS_MONK.RISING_SUN_KICK_TALENT.id,
  TALENTS_MONK.THUNDER_FOCUS_TEA_TALENT.id,
  TALENTS_MONK.LIFE_COCOON_TALENT.id,
];

export const WINDWALKER_HEART_SPELLS = [
  TALENTS_MONK.RISING_SUN_KICK_TALENT.id,
  TALENTS_MONK.FISTS_OF_FURY_TALENT.id,
  TALENTS_MONK.STRIKE_OF_THE_WINDLORD_TALENT.id,
  TALENTS_MONK.WHIRLING_DRAGON_PUNCH_TALENT.id,
];

// talent tree order, used to order statistics (position 0 is the hero talent summary)
// top talent, each column from left to right, then capstone
export const CONDUIT_TALENT_ORDER: Talent[] = [
  TALENTS_MONK.CELESTIAL_CONDUIT_MISTWEAVER_TALENT,
  TALENTS_MONK.CELESTIAL_CONDUIT_WINDWALKER_TALENT,
  TALENTS_MONK.TEMPLE_TRAINING_TALENT,
  TALENTS_MONK.XUENS_GUIDANCE_TALENT,
  TALENTS_MONK.JADE_SANCTUARY_TALENT,
  TALENTS_MONK.NIUZAOS_PROTECTION_TALENT,
  TALENTS_MONK.COURAGE_OF_THE_WHITE_TIGER_TALENT,
  TALENTS_MONK.STRENGTH_OF_THE_BLACK_OX_TALENT,
  TALENTS_MONK.STAMPEDE_OF_THE_ANCIENTS_TALENT,
  TALENTS_MONK.YULONS_KNOWLEDGE_TALENT,
  TALENTS_MONK.RESTORE_BALANCE_TALENT,
  TALENTS_MONK.PATH_OF_THE_FALLING_STAR_TALENT,
  TALENTS_MONK.INNER_COMPASS_TALENT,
  TALENTS_MONK.HEART_OF_THE_JADE_SERPENT_TALENT,
  TALENTS_MONK.YULONS_AVATAR_TALENT,
  TALENTS_MONK.FLOWING_WISDOM_TALENT,
  TALENTS_MONK.UNITY_WITHIN_TALENT,
];
